name = "EchelleSpectra"
uuid = "e42e2a4f-7e48-49c4-9e9a-180127d117fc"
authors = ["Bryson Cale <bryson.cale1@gmail.com>"]
version = "0.2.0"

[deps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
FITSIO = "0.17.1"
PyCall = "1.95.2"
julia = "1.9"
